#!/bin/bash
#Test2
#retourne la date et l heure de modification du fichier
jour=$(stat $1 | awk ' $1=="Modify:" {print $2}')
heure=$(stat $1 | awk ' $1=="Modify:" {print $3}')
echo "Ce fihier a ete mofifie a $heure le $jour" 
