#!/bin/bash
#compare l'arboresence des 2 dossiers, verifie si des fichiers sont présents sur les 2 dossiers et remplace l'ancien par le nouveau
#si un fichier n'est pas présent dans l'autre dossier, le copie le fichier dans l'autre dossier

historique=""



function synchro() {

        for fich in `ls $1`
        do
                typedefich=$(file "$1/$fich" | awk 'BEGIN{FS=": "} {print $2}')
                echo $typedefich

                if [[ "$typedefich" != "directory" ]]
                then
                        #on regarde si le fichier existe dans l'autre dossier
                        isinotherfolder=$(find "$2" -type f -name "$fich")

                        if [[ "$isinotherfolder" != "" ]]
                        then
                                echo "$fich est dans les 2 dossier"
                                #on compare leurs date de modif et on remplace le plus vieux par le plus recent
                                if [[ $1/$fich -ot $2/$fich ]]
                                then
                                        echo "Le fichier du dossier 2 est plus récent que celui du dossier 1"
                                        echo "2 -> 1"
                                        cp -f $2/$fich $1/$fich
                                else
                                        echo "Le fichier du dossier 2 est plus récent que celui du dossier 1"
                                        echo "1 -> 2"
                                        cp -f $1/$fich $2/$fich
                                fi
                        else
                                #si il n'est pas dans l'autre dossier on le copie directement dans l'autre dossier
                                echo "$fich n'est que dans le dossier 1"
                                cp -f $1/$fich $2/$fich
                        fi
                        #on ecrit le nom du fichier que l'on viens de traiter dans l'historique pour ne pas le remodifier dans la boucle d'après
                        historique="${historique} $fich"
                else
                        isinotherfolder=$(find "$2" -type d -name "$fich")
                        echo $isinotherfolder

                        if [[ "$isinotherfolder" != "" ]]
                        then
                                echo "Déjà présent dans l'autre dossier"
                                echo "Le folder1 est $1"
                                synchro "$1/$fich" "$2/$fich"
                                echo "Le folder1 est $1"
                        else
                                echo "recursive $1/$fich $2/$fich"
                                mkdir $2/$fich
                                synchro "$1/$fich" "$2/$fich"
                        fi
                fi
        done

        #meme princpie que la boucle d'avant mais cette fois ci on verife juste si les fichiers n'existent pas dans l'autre dossier et donc si il n'a pas été traité
        for fich in `ls $2`
        do
                typedefich=$(file "$2/$fich" | awk 'BEGIN{FS=": "} {print $2}')
                echo $typedefich

                if [[ "$typedefich" != "directory" ]]
                then

                        isinotherfolder=$(find "$1" -type f -name "$fich")

                        if [[ "$isinotherfolder" == "" ]]
                        then
                                echo "$fich n'est que dans le dossier 2"
                                cp -f $2/$fich $1/$fich
                        fi
                        historique="${historique} $fich"
                else
                        isinotherfolder=$(find "$2" -type d -name "$fich")

                        if [[ "$isinotherfolder" != "" ]]
                        then
                                echo "Déjà présent dans l'autre dossier"
                                synchro "$1/$fich" "$2/$fich"
                        else
                                echo "recursive $1/$fich $2/$fich"
                                mkdir $1/$fich
                                synchro "$1/$fich" "$2/$fich"
                        fi
                fi
        done

}

synchro $1 $2

echo "Synchronisation terminée"
