#!/bin/bash
#compare l'arboresence des 2 dossiers, verifie si des fichiers sont présents sur les 2 dossiers et remplace l'ancien par le nouveau
#si un fichier n'est pas présent dans l'autre dossier, le copie le fichier dans l'autre dossier

historique=""
echo '' > journaltemp

function ecrirejournal() {
        name="name: "$(stat -c%n $1 | awk 'BEGIN{FS="/"; OFS="/"} {$1="";print $0}')
        mode="mode: "$(stat -c%a $1)
        taille="taille: "$(stat -c%B $1)
        date="date: "$(stat -c%y $1)

        line="${name} ${mode} ${taille} ${date}"

        echo $line >> journaltemp
}

function comparejournal() {
        line=$(grep "$1" journal)
        mode=$(echo $line | awk 'BEGIN{FS=" "} {print $4}')
        taille=$(echo $line | awk 'BEGIN{FS=" "} {print $6}')
        date=$(echo $line | awk 'BEGIN{FS=" "} {print $8}')

        echo "line : $line"
        echo "mode : $mode"
        echo "taille : $taille"
        echo "date : $date"
}



function synchro() {

        for fich in `ls $1`
        do

                echo "Le fichier est $1/$fich"
                typedefich=$(file "$1/$fich" | awk 'BEGIN{FS=": "} {print $2}')
                echo "Le type du fichier est : $typedefich"

                if [[ "$typedefich" != "directory" ]]
                then

                        folder=$(echo $1 | awk 'BEGIN{FS="/"; OFS="/"} {$1="";print $0}')
                        echo "$folder/$fich "
                        isinjournal=$(grep "$folder/$fich " journal)
                        isinjournaltemp=$(grep "$folder/$fich " journaltemp)
                        echo "isinjournal : $isinjournal"
                        echo "isinjournaltemp : $isinjournaltemp"

                        if [[ "$isinjournal" != "" ]] && [[ "$isinjournaltemp" == "" ]]
                        then

                                echo "$fich est dans les 2 dossier"
                                #on compare leurs date de modif et on remplace le plus vieux par le plus recent
                                comparejournal $folder/$fich
                                if [[ $1/$fich -ot $2/$fich ]]
                                then
                                        echo "Le fichier du dossier $2 est plus récent que celui du dossier $1"
                                        echo "2 -> 1"
                                        cp -f $2/$fich $1/$fich
                                else
                                        echo "Le fichier du dossier $1 est plus récent que celui du dossier $2"
                                        echo "1 -> 2"
                                        cp -f $1/$fich $2/$fich
                                fi

                                ecrirejournal $1/$fich
                                echo "......................................................"

                        elif [[ "$isinjournal" == "" ]] && [[ "$isinjournaltemp" == "" ]]
                        then
                                #si il n'est pas dans l'autre dossier on le copie directement dans l'autre dossier
                                echo "$fich n'est que dans le dossier $1"
                                cp -f $1/$fich $2/$fich

                                ecrirejournal $1/$fich
                                echo "......................................................"
                        fi
                        #on ecrit le nom du fichier que l'on viens de traiter dans l'historique pour ne pas le remodifier dans la boucle d'après
                        #historique="${historique} $fich"
                else
                        isinotherfolder=$(find "$2" -type d -name "$fich")

                        if [[ "$isinotherfolder" != "" ]]
                        then
                                echo "Le dossier $1/$fich est présent dans le dossier $2"
                                echo "//////////////////////////////////////////////////"
                                synchro "$1/$fich" "$2/$fich"
                                echo "--------------------------------------------------"
                        else
                                echo "Le dossier $1/$fich n'est pas présent dans le dossier $2"
                                mkdir $2/$fich
                                echo "//////////////////////////////////////////////////"
                                synchro "$1/$fich" "$2/$fich"
                                echo "--------------------------------------------------"
                        fi
                fi

        done

        #meme princpie que la boucle d'avant mais cette fois ci on verife juste si les fichiers n'existent pas dans l'autre dossier et donc si il n'a pas été traité
        for fich in `ls $2`
        do

                echo "Le fichier est $2/$fich"
                typedefich=$(file "$2/$fich" | awk 'BEGIN{FS=": "} {print $2}')
                echo "Le  type du fichier est $typedefich"

                if [[ "$typedefich" != "directory" ]]
                then

                        folder=$(echo $1 | awk 'BEGIN{FS="/"; OFS="/"} {$1="";print $0}')
                        isinjournal=$(grep "$folder/$fich " journal)
                        isinjournaltemp=$(grep "$folder/$fich " journaltemp)
                        echo "isinjournal : $isinjournal"
                        echo "isinjournaltemp : $isinjournaltemp"

                        if [[ "$isinjournal" == "" ]] && [[ "$isinjournatemp" == "" ]]
                        then
                                echo "$2/$fich n'est que dans le dossier $2"
                                cp -f $2/$fich $1/$fich
                                #historique="${historique} $fich"
                                ecrirejournal $2/$fich
                                echo "..............................................................."
                        fi
                else
                        isinotherfolder=$(find "$1" -type d -name "$fich")

                        if [[ "$isinotherfolder" != "" ]]
                        then
                                echo "Le dossier $2/$fich est déjà présnent dans $1"
                                echo "//////////////////////////////////////////////////"
                                synchro "$2/$fich" "$1/$fich"
                                echo "--------------------------------------------------"
                        else
                                echo "Le dossier $2/$fich n'est pas présnent dans $1"
                                mkdir $1/$fich
                                echo "//////////////////////////////////////////////////"
                                synchro "$2/$fich" "$1/$fich"
                                echo "--------------------------------------------------"
                        fi
                fi
        done

}

function mkjournal() {

        for fich in `ls $1`
        do
                typedefich=$(file "$1/$fich" | awk 'BEGIN{FS=": "} {print $2}')
                if [[ "$typedefich" != "directory" ]]
                then
                        folder=$(echo $1 | awk 'BEGIN{FS="/"; OFS="/"} {$1="";print $0}')
                        isinjournal=$(grep "$folder/$fich " journaltemp)
                        if [[ "$isinjournal" == "" ]]
                        then
                                if [[ $1/$fich -ot $2/$fich ]]
                                then
                                        cp -f $2/$fich $1/$fich
                                else
                                        cp -f $1/$fich $2/$fich
                                fi
                                ecrirejournal $1/$fich
                        fi
                else
                        isinotherfolder=$(find "$2" -type d -name "$fich")

                        if [[ "$isinotherfolder" != "" ]]
                        then
                                mkjournal $1/$fich $2/$fich
                        else
                                mkdir $2/$fich
                                mkjournal $1/$fich $2/$fich
                        fi
                fi
        done

        for fich in `ls $2`
        do
                typedefich=$(file "$2/$fich" | awk 'BEGIN{FS=": "} {print $2}')
                if [[ "$typedefich" != "directory" ]]
                then
                        folder=$(echo $1 | awk 'BEGIN{FS="/"; OFS="/"} {$1="";print $0}')
                        isinjournal=$(grep "$folder/$fich " journaltemp)
                        if [[ "$isinjournal" == "" ]]
                        then
                                if [[ $1/$fich -ot $2/$fich ]]
                                then
                                        cp -f $2/$fich $1/$fich
                                else
                                        cp -f $1/$fich $2/$fich
                                fi
                                ecrirejournal $1/$fich
                        fi
                else
                        isinotherfolder=$(find "$1" -type d -name "$fich")

                        if [[ "$isinotherfolder" != "" ]]
                        then
                                mkjournal $2/$fich $1/$fich
                        else
                                mkdir $1/$fich
                                mkjournal $2/$fich $1/$fich
                        fi
                fi
        done

        cat journaltemp > journal
}


isjournalvide=$(wc -c journal | awk 'BEGIN{FS=" "} {print $1}')

if [[ $isjournalvide -eq 1 ]]
then
        echo "Le fichier journal est vide"
        mkjournal $1 $2
else
        synchro $1 $2
fi

cat journaltemp > journal

echo "Synchronisation terminée"

cat ../logo
