#!bin/bash
#compare l'arborescence des 2 dossiers, verifie si des fichiers sont présents sur les 2 dossiers et remplace l'ancien par le nouveau
#si un fichier ou répertoire n'est pas présent dans l'autre dossier, on copie le fichier dans l'autre dossier

historique=""
function synchro() {
for fich in `ls $1`
do
        typedefich=$(file "$1/$fich" | awk 'BEGIN{FS=": "} {print $2}')
        echo $typedefich

        if [[ "$typedefich" != "directory" ]]
        then
                #On regarde si le fichier existe dans l'autre dossier
                isinotherfolder=$(find "$2" -type f -name "$fich")

                if [[ "$isinotherfolder" != "" ]]
                then

                        echo "$fich est dans les 2 dossiers"
                        #On compare leurs date de modif et on remplace le plus vieux par le plus recent
                        if [[ $1/$fich -ot $2/$fich ]]
                        then

                                echo "Le fichier du dossier 2 est plus récent que celui du dossier 1"
                                echo "2 -> 1"
                                cp -f $2/$fich $1/$fich
                        else
                                echo "Le fichier du dossier 1 est plus récent que celui du dossier 2"
                                echo "1 -> 2"
                                cp -f $1/$fich $2/$fich
                        fi
                else
                #Si il n'est pas dans l'autre dossier on le copie directement dans l'autre dossier
                echo "$fich n'est que dans le dossier 1"
                cp -f $1/$fich $2/$fich
                fi
                #On écrit le nom du fichier que l'on vient de traiter dans l'historique pour ne pas le remodifier par la suite
                historique="${historique} $fich"
        else
                isinotherfolder=$(find "$2" -type d -name "$fich")
                echo "isinotherfolder"

                if [[ "isinotherfolder" != "" ]]
                then
                        echo "Déjà présent dans l'autre dossier"
                        echo "Le folder1 est $1"
                        synchro "$1/$fich" "$2/$fich"
                else
                        echo "recursive $1/$fich $2/$fich"
                        mddir $2/$fich
                        synchro "$1/$fich" "$2/$fich"
                fi
        fi
done

#Même principe pour le 2e dossier mais on verifie seulement pour ceux qui ne sont pas dans l'autre dossier

for fich in `ls $folder2`
do
        typedefich=$(file "$2/$fich" | awk 'BEGIN{FS=": "} {print $2}')
        echo $typedefich

        if [[ "$typedefich" != "directory" ]]
        then

                isinotherfolder=$(find $1 -type f -name $fich)

                if [[ "$isinotherfolder" == "" ]]
                then
                        echo "$fich nest que dans le dossier2"
                        cp -f $2/$fich $1/$fich
                fi
                historique="${historique} $fich"
        else
                isinotherfolder=$(find "$2" -type f -name "$fich")
                if [[ "isinotherfolder" != "" ]]
                then
                        echo "Déjà present dans lautre dossier"
                        synchro "$1/$fich" "$2/$fich"
                else
                        echo "recursive $1/$fich $2/$fich"
                        mkdir $1/fich
                        synchro "$1/$fich" "$2/$fich"
                fi
        fi
done
}
synchro $1 $2
